<img style="float: left; margin: 30px 15px 15px 15px;" src="https://pngimage.net/wp-content/uploads/2018/06/logo-iteso-png-5.png" width="300" height="500" /> 
    
    
### <font color='navy'> Simulación de procesos financieros. 

**Nombres:** Alejandra Rico Rosales, Frida María Hernández López.

**Fecha:** 09 de septiembre del 2021.

**Expediente:** 720838, 720476.
    
**Profesor:** Oscar David Jaramillo Zuluaga.
    
**Link Github:** [Link con el enlace del repositorio del creador del proyecto](https://github.com/alerrico/Tarea2_ARico_FMHernandez)

# Tarea 2: Clase 4

In [2]:
import pandas as pd
import numpy as np
from functools import reduce

## Enunciado de tarea (Transcribirlo)

> 1. Imagine una rutina contable utilizada en una librería. Funciona en una lista con sublistas. Escriba un programa en Python, que devuelve una lista con tuplas de tamaño 2. Cada tupla consiste en el número de pedido y el costo total del pedido. El producto debe aumentarse en 10€ si el valor de la orden es inferior a 100,00 €. 
Escribe un programa Python usando unicamente las funciones **lambda y map**.

#### Código de solución `ESTUDIANTE 1: ALEJANDRA RICO`

In [3]:
orders = [["34587", "Learning Python, Mark Lutz", 4, 40.95], 
          ["98762", "Programming Python, Mark Lutz", 5, 56.80], 
          ["77226", "Head First Python, Paul Barry", 3,32.95],
          ["88112", "Einführung in Python3, Bernd Klein", 3, 24.99]]

r1 = list(map(lambda n: (n[0], n[2]*n[3] if n[2]*n[3] >= 100 else n[2]*n[3]+10), orders))
r1

[('34587', 163.8),
 ('98762', 284.0),
 ('77226', 108.85000000000001),
 ('88112', 84.97)]

#### Código de solución `ESTUDIANTE 2: FRIDA HERNÁNDEZ`

In [2]:
import numpy as np
orders = [ ["34587", "Learning Python, Mark Lutz", 4, 40.95], 
           ["98762", "Programming Python, Mark Lutz", 5, 56.80], 
           ["77226", "Head First Python, Paul Barry", 3,32.95],
           ["88112", "Einführung in Python3, Bernd Klein", 3, 24.99]]
mult =lambda x,y:x*y
def aumenta(v):
    if v<100:
        v+=10
    return v
x= list(map(aumenta,[mult(orders[i][2],orders[i][3]) for i in np.arange(len(orders))]))
list(map(lambda x,y:(x[0],y),orders,x))

[('34587', 163.8),
 ('98762', 284.0),
 ('77226', 108.85000000000001),
 ('88112', 84.97)]

> 2. La misma librería, pero esta vez trabajamos en una lista diferente. Las sublistas de nuestras listas se ven así: 
[número de orden, (número de artículo, cantidad, precio por unidad), ... (número de artículo, cantidad, precio por unidad)]. Escriba un programa que devuelva una lista de dos tuplas que tengan la información de (número de pedido, cantidad total de pedido). Utilice la función `Reduce`. Recuerde el precio del pedido del producto debe aumentarse en 10€ si el valor de la orden es inferior a 100,00 €.

#### Código de solución `ESTUDIANTE 1: ALEJANDRA RICO`

In [5]:
orders2 = [[1, ("5464", 4, 9.99), ("8274",18,12.99), ("9744", 9, 44.95)], 
          [2, ("5464", 9, 9.99), ("9744", 9, 44.95)],
          [3, ("5464", 9, 9.99), ("88112", 11, 24.99)],
          [4, ("8732", 7, 11.99), ("7733",11,18.99), ("88112", 5, 39.95)]]
r2 = list(map(lambda x: [x[0]] + list(map(lambda y: y[1]*y[2] if y[1]*y[2]>=100 else y[1]*y[2]+10, x[1:])), orders2))

r2 = list(map(lambda x: [x[0]]+ \
                         [reduce(lambda a,b: a+b, x[1:])], r2))
r2

[[1, 688.3299999999999],
 [2, 504.46000000000004],
 [3, 374.79999999999995],
 [4, 502.57]]

#### Código de solución `ESTUDIANTE 2: FRIDA HERNÁNDEZ`

In [3]:
orders1 = [[1, ("5464", 4, 9.99), ("8274",18,12.99), ("9744", 9, 44.95)], 
          [2, ("5464", 9, 9.99), ("9744", 9, 44.95)],
          [3, ("5464", 9, 9.99), ("88112", 11, 24.99)],
           [4, ("8732", 7, 11.99), ("7733",11,18.99), ("88112", 5, 39.95)] ]

from functools import reduce
sol1 =list(map(lambda x: [x[0]] + list(map(lambda y: y[1]*y[2] 
                    if y[1]*y[2]>=100 else y[1]*y[2] +10 , x[1:])), orders1))

list(map(lambda x: [x[0]] + [reduce(lambda a,b: a + b, x[1:])], sol1))

[[1, 688.3299999999999],
 [2, 504.46000000000004],
 [3, 374.79999999999995],
 [4, 502.57]]

> 3. Resolver los anteriores ejercicios usando pandas (DataFrame)

#### Código de solución `ESTUDIANTE 1: ALEJANDRA RICO`

##### Ejercicio 1

In [6]:
orders = [["34587", "Learning Python, Mark Lutz", 4, 40.95], 
          ["98762", "Programming Python, Mark Lutz", 5, 56.80], 
          ["77226", "Head First Python, Paul Barry", 3,32.95],
          ["88112", "Einführung in Python3, Bernd Klein", 3, 24.99]]

df1 = pd.DataFrame(data=orders, columns=['Número de pedido','Nombre','Cantidad','Costo individual'])
ct = list(map(lambda n: (n[2]*n[3] if n[2]*n[3]>=100 else n[2]*n[3] +10),orders)) 
df1['TOTAL']= ct
df1.iloc[:,[0,4]]

Número de pedido   TOTAL
0            34587  163.80
1            98762  284.00
2            77226  108.85
3            88112   84.97

##### Ejercicio 2

In [8]:
orders2 = [[1, ("5464", 4, 9.99), ("8274",18,12.99), ("9744", 9, 44.95)], 
          [2, ("5464", 9, 9.99), ("9744", 9, 44.95)],
          [3, ("5464", 9, 9.99), ("88112", 11, 24.99)],
          [4, ("8732", 7, 11.99), ("7733",11,18.99), ("88112", 5, 39.95)]]

df2 = pd.DataFrame(data=orders2, columns=['Número de pedido','Nombre','Cantidad','Costo individual'])
ct2 = list(map(lambda x: [x[0]] + list(map(lambda y: y[1]*y[2] if y[1]*y[2]>=100 else y[1]*y[2]+10, x[1:])), orders2))
ct2 =list(map(lambda x: reduce(lambda a,b: a+b, x[1:]), r2))
df2['TOTAL']= ct2
df2.iloc[:,[0,4]]

Número de pedido   TOTAL
0                 1  688.33
1                 2  504.46
2                 3  374.80
3                 4  502.57

#### Código de solución `ESTUDIANTE 2: FRIDA HERNÁNDEZ`

##### Ejercicio 1

In [7]:
import pandas as pd
df=pd.DataFrame(columns=["Orden","Libro & Autor","Cantidad","Precio por unidad"], data=orders)
res=[(df.iloc[##### Ejercicio 1:,-2]*df.iloc[:,-1]).apply(lambda x: x if x>=100 else (x+10))]

res=pd.DataFrame(res)
res=res.append(df.iloc[:,0])
res.T

0  Orden
0   163.8  34587
1     284  98762
2  108.85  77226
3   84.97  88112

##### Ejercicio 2

In [27]:
orders2 = [[1, "5464", 4, 9.99, "8274",18,12.99, "9744", 9, 44.95], 
           [2, "5464", 9, 9.99, "9744", 9, 44.95, 0,0,0],
           [3, "5464", 9, 9.99, "88112", 11, 24.99, 0,0,0],
           [4, "8732", 7, 11.99, "7733",11,18.99, "88112", 5, 39.95]]

df1=pd.DataFrame(data=orders2)

res1= [((df1.iloc[:,2]*df1.iloc[:,3])+(df1.iloc[:,5]*df1.iloc[:,6])+(df1.iloc[:,8]*df1.iloc[:,9])).apply(lambda x: x if x>=100 else (x+10))]
res1=pd.DataFrame(res1)
res1.T

0
0  678.33
1  494.46
2  364.80
3  492.57

> 4. Use filter to eliminate all words that are shorter than 4 letters from a list of words
`list='the notion of a lambda function goes all the way back to the origin of computer science'`

#### Código de solución `ESTUDIANTE 1: ALEJANDRA RICO`

In [9]:
lista = 'the notion of a lambda function goes all the way back to the origin of computer science'
words = lista.split()
r4 = list(filter(lambda x: len(x)>4, words))
r4

['notion', 'lambda', 'function', 'origin', 'computer', 'science']

#### Código de solución `ESTUDIANTE 2: FRIDA HERNÁNDEZ`

In [28]:
lista=['the','notion','of','a','lambda','function','goes','all','the','way','back','to','the','origin','of','computer','science']
list(filter(lambda x: x if len(x) >=4 else None, lista))

['notion',
 'lambda',
 'function',
 'goes',
 'back',
 'origin',
 'computer',
 'science']

> 5. Use filter to determine the percentage of Fahrenheit temperatures in a list are within the range 32 to 80

In [30]:
np.random.seed(55555)
temperatures = np.random.uniform(25,110,30)
print(temperatures)

[ 35.97387961  99.13294268  92.6178302   99.69549478  63.21119535
  73.90387697  95.50028838  99.21476553  36.98251238 101.45813729
 100.5917418   89.38159435  89.52156589  83.8084752   28.37990868
  68.75395211  45.86132067  36.58307493  56.32208365  33.96219302
  45.29071318  74.86289938  66.51091383  88.19316186  94.26635864
  46.83131624 109.60744472 109.68427993  44.55796499  92.84146259]


#### Código de solución `ESTUDIANTE 1: ALEJANDRA RICO`

In [11]:
temp = list(temperatures)
r5 = list(filter(lambda x: 80>= x >= 32 , temp))
r5

[35.97387961379455,
 63.211195349983264,
 73.90387696517755,
 36.982512376595906,
 68.75395211338406,
 45.86132066984196,
 36.58307493022292,
 56.322083650154724,
 33.9621930206693,
 45.29071317816652,
 74.86289938282341,
 66.51091382521807,
 46.831316244170544,
 44.55796498523391]

In [12]:
print('El porcentaje es:', len(r5)/len(temp)*100)

El porcentaje es: 46.666666666666664


#### Código de solución `ESTUDIANTE 2: FRIDA HERNÁNDEZ`

In [31]:
rango=list(filter(lambda x: x if x >=32 and x<=80 else None, temperatures))
percentage=lambda x,t: len(x)/len(t)
print(percentage(rango,temperatures)*100, "%")

46.666666666666664 %


> 6. Use reduce to find the lower left corner (minimum x and minimum y value) for a list of point locations.

> **Hint**: Explore the command `np.minimum.reduce` [link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ufunc.reduce.html)

In [33]:
np.random.seed(55555)
point_xy = np.random.randint(0,100,[30,2])
print(point_xy)

[[17 97]
 [22 33]
 [37 46]
 [57 28]
 [11 25]
 [14  2]
 [74 16]
 [12 37]
 [35 21]
 [66 65]
 [86 58]
 [67 81]
 [ 0 48]
 [28 66]
 [76 22]
 [46 47]
 [64  7]
 [88 94]
 [65 13]
 [75 89]
 [23 17]
 [36 63]
 [62 36]
 [64 17]
 [18 19]
 [88 41]
 [21 49]
 [98 36]
 [81 73]
 [62 90]]


#### Código de solución `ESTUDIANTE 1: ALEJANDRA RICO`

In [14]:
r6 = np.minimum.reduce(point_xy)
r6

array([0, 2])

#### Código de solución `ESTUDIANTE 2: FRIDA HERNÁNDEZ`

In [35]:
np.minimum.reduce(point_xy)

array([0, 2])